config/routes.rb
Rails.application.routes.draw do
  root to: 'shops#search'

  devise_for :users
  resources :shops, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    collection do
      get 'search', to: 'shops#search', as: 'search'
      get 'search_by_reviews', to: 'shops#search_by_reviews', as: 'search_by_reviews'
    end
    member do
      get 'reviews', to: 'shops#reviews'
      get 'photos', to: 'shops#photos'
    end
    resources :reviews, only: [:new, :create, :show, :edit, :update, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index]
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  def self.search(search)
    if search != ""
      Shop.where('shop_name LIKE(?)', "%#{search}%")
    else
      Shop.all
    end
  end

  def average_cleanliness
    reviews.average(:cleanliness).to_f
  end

  def average_lighting
    reviews.average(:lighting).to_f
  end

  def average_music
    reviews.average(:music).to_f
  end

  def average_space
    reviews.average(:space).to_f
  end

  def average_vibrancy
    reviews.average(:vibrancy).to_f
  end

  def average_order_speed
    reviews.average(:order_speed).to_f
  end

  def average_service_style
    reviews.average(:service_style).to_f
  end

  def average_conversation
    reviews.average(:conversation).to_f
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]

  def search
    
  end

  def index
    if params[:keyword].present?
      @shops = Shop.where('shop_name LIKE ?', "%#{params[:keyword]}%")
    else
      @shops = Shop.all
    end
  end

  def search_by_reviews
    @shops = Shop.all

    @shops = @shops.sort_by do |shop|
      diffs = []

      diffs << (shop.average_cleanliness - params[:cleanliness].to_f).abs if params[:cleanliness].present? && params[:cleanliness].to_f != 0
      diffs << (shop.average_lighting - params[:lighting].to_f).abs if params[:lighting].present? && params[:lighting].to_f != 0
      diffs << (shop.average_music - params[:music].to_f).abs if params[:music].present? && params[:music].to_f != 0
      diffs << (shop.average_space - params[:space].to_f).abs if params[:space].present? && params[:space].to_f != 0
      diffs << (shop.average_vibrancy - params[:vibrancy].to_f).abs if params[:vibrancy].present? && params[:vibrancy].to_f != 0
      diffs << (shop.average_order_speed - params[:order_speed].to_f).abs if params[:order_speed].present? && params[:order_speed].to_f != 0
      diffs << (shop.average_service_style - params[:service_style].to_f).abs if params[:service_style].present? && params[:service_style].to_f != 0
      diffs << (shop.average_conversation - params[:conversation].to_f).abs if params[:conversation].present? && params[:conversation].to_f != 0

      diffs.sum
    end

    if params[:wifi].present?
      @shops = @shops.select { |shop| shop.wifi == params[:wifi] }
    end

    if params[:price_range].present?
      @shops = @shops.select { |shop| shop.price_range == params[:price_range] }
    end

    if params[:smoking].present?
      @shops = @shops.select { |shop| shop.smoking == params[:smoking] }
    end

    render :index
  end

  def show
    @shop = Shop.find(params[:id])
  end

  def reviews
    @shop = Shop.find(params[:id])    
  end

  def photos
    @shop = Shop.find(params[:id])
    @photos = @shop.reviews.map(&:images).flatten
  end

  def new
    @shop_review = ShopReview.new
    
  end

  def create
    @shop_review = ShopReview.new(shop_review_params)
    if @shop_review.valid?
      @shop_review.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @shop = Shop.find(params[:id])
    if current_user.id != @shop.user_id
      redirect_to shop_path(@shop)
    end
  end

  def update
    @shop = Shop.find(params[:id])
    if @shop.update(shop_params)
      redirect_to shop_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    shop = Shop.find(params[:id])
    if current_user.id == shop.user_id
      shop.destroy
      redirect_to root_path
    else
      redirect_to shop_path(shop.id)
    end
  end

  private
  def shop_review_params
    permitted_params = params.require(:shop_review).permit(
      :shop_name, :cuisine_type, :closed_days, :opening_hours, :address, :phone_number, :additional_info, :wifi, :smoking, :latitude, :longitude,:price_range,
      :cleanliness, :space, :lighting, :music, :vibrancy, :order_speed, :service_style, :conversation, :description, payment_methods: [],images: []
    )
    permitted_params.merge(user_id: current_user.id, payment_methods: permitted_params[:payment_methods].join(','))
  end
  
  def shop_params
    permitted_params = params.require(:shop).permit(
      :shop_name, :cuisine_type, :closed_days, :opening_hours, :address, :phone_number, :additional_info, :wifi, :smoking, :latitude, :longitude, :price_range,
      payment_methods: []
    )
    
    permitted_params.merge(user_id: current_user.id, payment_methods: permitted_params[:payment_methods].join(','))
  end
  
end

app/helpers/shops_helper.rb
module ShopsHelper
  def label_for_cleanliness(value)
    case value
    when -3 then "ヴィンテージ"
    when -2 then "ややヴィンテージ"
    when -1 then "少しヴィンテージ"
    when 0 then "どちらとも言えない"
    when 1 then "少しピカピカ"
    when 2 then "ややピカピカ"
    when 3 then "ピカピカ"
    end
  end

  def label_for_lighting(value)
    case value
    when -3 then "暗い"
    when -2 then "やや暗い"
    when -1 then "少し暗い"
    when 0 then "どちらとも言えない"
    when 1 then "少し明るい"
    when 2 then "やや明るい"
    when 3 then "明るい"
    end
  end

  def label_for_music(value)
    case value
    when -3 then "クラシック"
    when -2 then "ややクラシック"
    when -1 then "少しクラシック"
    when 0 then "どちらとも言えない"
    when 1 then "少しモダン"
    when 2 then "ややモダン"
    when 3 then "モダン"
    end
  end

  def label_for_space(value)
    case value
    when -3 then "狭い"
    when -2 then "やや狭い"
    when -1 then "少し狭い"
    when 0 then "どちらとも言えない"
    when 1 then "少し広い"
    when 2 then "やや広い"
    when 3 then "広い"
    end
  end

  def label_for_vibrancy(value)
    case value
    when -3 then "しっとり"
    when -2 then "ややしっとり"
    when -1 then "少ししっとり"
    when 0 then "どちらとも言えない"
    when 1 then "少しワイワイ"
    when 2 then "ややワイワイ"
    when 3 then "ワイワイ"
    end
  end

  def label_for_order_speed(value)
    case value
    when -3 then "ゆったり"
    when -2 then "ややゆったり"
    when -1 then "少しゆったり"
    when 0 then "どちらとも言えない"
    when 1 then "少しテキパキ"
    when 2 then "ややテキパキ"
    when 3 then "テキパキ"
    end
  end

  def label_for_service_style(value)
    case value
    when -3 then "ジェントル"
    when -2 then "ややジェントル"
    when -1 then "少しジェントル"
    when 0 then "どちらとも言えない"
    when 1 then "少しフレンドリー"
    when 2 then "ややフレンドリー"
    when 3 then "フレンドリー"
    end
  end

  def label_for_conversation(value)
    case value
    when -3 then "寡黙"
    when -2 then "やや寡黙"
    when -1 then "少し寡黙"
    when 0 then "どちらとも言えない"
    when 1 then "少しおしゃべり"
    when 2 then "ややおしゃべり"
    when 3 then "おしゃべり"
    end
  end
end

app/views/shops/edit.html.erb
<%= render "shared/header" %>

<h1><%= @shop.shop_name %> を編集</h1>

<%= form_with model: @shop, local: true do |form| %>
  <h2>お店の基本情報</h2>

  <div id="map" style="height: 400px;" data-controller="map" data-map-latitude-target="latitude" data-map-longitude-target="longitude">
    <%= form.hidden_field :latitude, id: "shop_latitude", data: { map_target: "latitude" } %>
    <%= form.hidden_field :longitude, id: "shop_longitude", data: { map_target: "longitude" } %>
  </div>

  <div class="form-group">
    <%= form.label :shop_name, "店名", class: 'form-label' %>
    <%= form.text_field :shop_name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :cuisine_type, "料理ジャンル", class: 'form-label' %>
    <%= form.text_field :cuisine_type, class: 'form-control' %>
  </div>


  <div class="form-group">
    <%= form.label :address, "住所", class: 'form-label' %>
    <%= form.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :opening_hours, "営業時間", class: 'form-label' %>
    <%= form.text_field :opening_hours, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :closed_days, "定休日", class: 'form-label' %>
    <%= form.text_field :closed_days, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :phone_number, "電話番号", class: 'form-label' %>
    <%= form.text_field :phone_number, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :additional_info, "追加情報", class: 'form-label' %>
    <%= form.text_area :additional_info, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :payment_methods, "支払い方法（複数選択可）" %>
    <div class="checkbox-group">
      <%= check_box_tag 'shop[payment_methods][]', '現金', @shop.payment_methods&.include?('現金') %> 現金<br>
      <%= check_box_tag 'shop[payment_methods][]', 'クレジットカード', @shop.payment_methods&.include?('クレジットカード') %> クレジットカード<br>
      <%= check_box_tag 'shop[payment_methods][]', '電子マネー', @shop.payment_methods&.include?('電子マネー') %> 電子マネー<br>
      <%= check_box_tag 'shop[payment_methods][]', 'QRコード決済', @shop.payment_methods&.include?('QRコード決済') %> QRコード決済<br>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :price_range, "価格帯", class: 'form-label' %>
    <div class="radio-group">
      <%= form.radio_button :price_range, 'ラグジュアリー', class: 'custom-radio' %>
      <%= form.label :price_range_luxury, "ラグジュアリー" %>
      <%= form.radio_button :price_range, 'スタンダード', class: 'custom-radio' %>
      <%= form.label :price_range_standard, "スタンダード" %>
      <%= form.radio_button :price_range, 'リーズナブル', class: 'custom-radio' %>
      <%= form.label :price_range_reasonable, "リーズナブル" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :wifi, "WiFi", class: 'form-label' %>
    <div class="radio-group">
      <%= form.radio_button :wifi, 'あり', class: 'custom-radio' %>
      <%= form.label :wifi_true, "あり" %>
      <%= form.radio_button :wifi, 'なし', class: 'custom-radio' %>
      <%= form.label :wifi_false, "なし" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :smoking, "タバコ", class: 'form-label' %>
    <div class="radio-group">
      <%= form.radio_button :smoking, '店内で喫煙可', class: 'custom-radio' %>
      <%= form.label :smoking_indoor, "店内で喫煙可" %>
      <%= form.radio_button :smoking, '加熱式のみ店内可', class: 'custom-radio' %>
      <%= form.label :smoking_heated, "加熱式のみ店内可" %>
      <%= form.radio_button :smoking, '店外でなら喫煙可', class: 'custom-radio' %>
      <%= form.label :smoking_outdoor, "店外でなら喫煙可" %>
      <%= form.radio_button :smoking, '喫煙不可', class: 'custom-radio' %>
      <%= form.label :smoking_none, "喫煙不可" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.submit "保存する", class: "btn btn-primary" %>
  </div>
<% end %>

<%= render "shared/footer" %>

app/views/shops/reviews.html.erb
<%= render "shared/header" %>
<div class="container">
  <h1><%= @shop.shop_name %> のレビュー 一覧</h1>

  <% if @shop.reviews.any? %>
    <table class="table">
      <thead>
        <tr>
          <th>ユーザー</th>
          <th>性別</th>
          <th>年代</th>
          <th>投稿日</th>
          <th>詳細</th>
        </tr>
      </thead>
      <tbody>
        <% @shop.reviews.each do |review| %>
          <tr>
            <td><%= review.user.nickname %></td>
            <td><%= review.user.gender.name %></td>
            <td><%= review.user.age_group.name %></td>
            <td><%= review.created_at.strftime("%Y-%m-%d") %></td>
            <td><%= link_to '詳細を見る', shop_review_path(@shop, review), class: 'btn btn-primary' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>まだレビューが投稿されていません。</p>
  <% end %>

  <%= link_to 'お店の詳細に戻る', shop_path(@shop), class: 'btn btn-primary' %>
</div>

<%= render "shared/footer" %>

app/views/shops/search.html.erb
<div class="image-slider">
    <div class="slider-content">
      <img src="<%= asset_path('iStock-1460592275.jpg') %>" alt="Image 1">
      <img src="<%= asset_path('iStock-1227451753.jpg') %>" alt="Image 2">
      <img src="<%= asset_path('iStock-1161794704.jpg') %>" alt="Image 3">
      <img src="<%= asset_path('iStock-1161790323.jpg') %>" alt="Image 4">
      <img src="<%= asset_path('iStock-1150749127.jpg') %>" alt="Image 5">
      <img src="<%= asset_path('iStock-1128235080.jpg') %>" alt="Image 6">
      <img src="<%= asset_path('iStock-1011313826.jpg') %>" alt="Image 7">
      <img src="<%= asset_path('iStock-975500428.jpg') %>" alt="Image 8">
  </div>
</div>
<%= render "shared/header" %>

<h1>お店を検索</h1>

<%= form_with url: shops_path, method: :get, local: true do |form| %>
  <h2>店名で検索する</h2>
  <%= form.text_field :keyword, placeholder: "検索キーワードを入力", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
<% end %>
<%= form_with url: search_by_reviews_shops_path, method: :get, local: true do |form| %>
  <h2>雰囲気で検索する</h2>
  <h2>お店の雰囲気</h2>
  <div class="form-group">
    <%= form.label :cleanliness, "清潔さ", class: 'form-label' %>
    <div class="radio-group">
      <span class="extreme-label">ヴィンテージ</span>
      <% (-3..3).each do |n| %>
        <div class="radio-item">
          <%= form.radio_button :cleanliness, n, id: "cleanliness_#{n}", checked: n == 0 %>
        </div>
      <% end %>
      <span class="extreme-label">ピカピカ</span>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :lighting, "照明", class: 'form-label' %>
    <div class="radio-group">
      <span class="extreme-label">暗い</span>
      <% (-3..3).each do |n| %>
        <div class="radio-item">
          <%= form.radio_button :lighting, n, id: "lighting_#{n}", checked: n == 0 %>
        </div>
      <% end %>
      <span class="extreme-label">明るい</span>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :music, "音楽", class: 'form-label' %>
    <div class="radio-group">
      <span class="extreme-label">クラシック</span>
      <% (-3..3).each do |n| %>
        <div class="radio-item">
          <%= form.radio_button :music, n, id: "music_#{n}", checked: n == 0 %>
        </div>
      <% end %>
      <span class="extreme-label">モダン</span>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :space, "広さ", class: 'form-label' %>
    <div class="radio-group">
      <span class="extreme-label">狭い</span>
      <% (-3..3).each do |n| %>
        <div class="radio-item">
          <%= form.radio_button :space, n, id: "space_#{n}", checked: n == 0 %>
        </div>
      <% end %>
      <span class="extreme-label">広い</span>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :vibrancy, "活気", class: 'form-label' %>
    <div class="radio-group">
      <span class="extreme-label">しっとり</span>
      <% (-3..3).each do |n| %>
        <div class="radio-item">
          <%= form.radio_button :vibrancy, n, id: "vibrancy_#{n}", checked: n == 0 %>
        </div>
      <% end %>
      <span class="extreme-label">ワイワイ</span>
    </div>
  </div>

  <h2>スタッフの雰囲気</h2>

  <div class="form-group">
    <%= form.label :order_speed, "オーダーの速さ", class: 'form-label' %>
    <div class="radio-group">
      <span class="extreme-label">ゆったり</span>
      <% (-3..3).each do |n| %>
        <div class="radio-item">
          <%= form.radio_button :order_speed, n, id: "order_speed_#{n}", checked: n == 0 %>
        </div>
      <% end %>
      <span class="extreme-label">テキパキ</span>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :service_style, "対応スタイル", class: 'form-label' %>
    <div class="radio-group">
      <span class="extreme-label">ジェントル</span>
      <% (-3..3).each do |n| %>
        <div class="radio-item">
          <%= form.radio_button :service_style, n, id: "service_style_#{n}", checked: n == 0 %>
        </div>
      <% end %>
      <span class="extreme-label">フレンドリー</span>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :conversation, "会話", class: 'form-label' %>
    <div class="radio-group">
      <span class="extreme-label">寡黙</span>
      <% (-3..3).each do |n| %>
        <div class="radio-item">
          <%= form.radio_button :conversation, n, id: "conversation_#{n}", checked: n == 0 %>
        </div>
      <% end %>
      <span class="extreme-label">おしゃべり</span>
    </div>
  </div>

  <h2>その他</h2>

  <div class="form-group">
    <%= form.label :price_range, "価格帯", class: 'form-label' %>
    <div class="radio-group">
      <%= form.radio_button :price_range, 'ラグジュアリー' ,class: 'custom-radio'%>
      <%= form.label :price_range_luxury, "ラグジュアリー" %>
      <%= form.radio_button :price_range, 'スタンダード' ,class: 'custom-radio'%>
      <%= form.label :price_range_standard, "スタンダード" %>
      <%= form.radio_button :price_range, 'リーズナブル',class: 'custom-radio' %>
      <%= form.label :price_range_reasonable, "リーズナブル" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :wifi, "WiFi", class: 'form-label' %>
    <div class="radio-group">
      <%= form.radio_button :wifi, 'あり' ,class: 'custom-radio'%>
      <%= form.label :wifi, "あり" %>
      <%= form.radio_button :wifi, 'なし' ,class: 'custom-radio'%>
      <%= form.label :wifi, "なし" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :smoking, "タバコ", class: 'form-label' %>
    <div class="radio-group">
      <%= form.radio_button :smoking, '店内で喫煙可',class: 'custom-radio'%>
      <%= form.label :smoking_indoor, "店内で喫煙可" %>
      <%= form.radio_button :smoking, '加熱式のみ店内可',class: 'custom-radio' %>
      <%= form.label :smoking_heated, "加熱式のみ店内可" %>
      <%= form.radio_button :smoking, '店外でなら喫煙可',class: 'custom-radio' %>
      <%= form.label :smoking_outdoor, "店外でなら喫煙可" %>
      <%= form.radio_button :smoking, '喫煙不可',class: 'custom-radio' %>
      <%= form.label :smoking_none, "喫煙不可" %>
    </div>
  </div>

  <%= form.submit "検索", class: "atmosphere-search-btn" %>
<% end %>

<%= render "shared/footer" %>

app/views/shops/show.html.erb
<%= render "shared/header" %>
<div class="container">
  <div class="tab-actions">
    <%= link_to '写真一覧を見る', photos_shop_path(@shop), class: 'tab-btn' %>
    <%= link_to 'レビュー 一覧を見る', reviews_shop_path(@shop), class: 'tab-btn' %>
    <%= link_to 'レビューを投稿する', new_shop_review_path(@shop), class: 'tab-btn' %>
  </div>

  <h1><%= @shop.shop_name %> の詳細</h1>
  <div id="map" style="height: 400px;" data-controller="map" data-map-latitude-target="latitude" data-map-longitude-target="longitude">
    <%= hidden_field_tag :latitude, @shop.latitude, id: "shop_latitude", data: { map_target: "latitude" } %>
    <%= hidden_field_tag :longitude, @shop.longitude, id: "shop_longitude", data: { map_target: "longitude" } %>
  </div>


  <div class="shop-details">
    <p><strong>お店の名前:</strong> <%= @shop.shop_name %></p>
    <p><strong>料理ジャンル:</strong> <%= @shop.cuisine_type %></p>
    <p><strong>住所:</strong> <%= @shop.address %></p>
    <p><strong>営業時間:</strong> <%= @shop.opening_hours %></p>
    <p><strong>定休日:</strong> <%= @shop.closed_days %></p>
    <p><strong>電話番号:</strong> <%= @shop.phone_number %></p>
    <p><strong>価格帯:</strong> <%= @shop.price_range %></p>
    <p><strong>支払い方法:</strong> <%= @shop.payment_methods %></p>
    <p><strong>WiFi:</strong> <%= @shop.wifi %></p>
    <p><strong>タバコ:</strong> <%= @shop.smoking %></p>
    <p><strong>追加情報:</strong> <%= @shop.additional_info %></p>
  </div>

  <h2>レビューの平均評価</h2>

  <div class="sd-evaluation">
    <!-- 清潔さ -->
    <div class="evaluation-item">
      <span class="label-top">清潔さ</span>
      <div class="label-container">
        <span class="label-left">ヴィンテージ</span>
        <div class="bar">
          <div class="neutral"></div>
          <% cleanliness_score = @shop.average_cleanliness %>
          <% cleanliness_width = cleanliness_score.abs / 3.0 * 50 %>
          <% if cleanliness_score != 0 %>
            <div class="fill <%= cleanliness_score.positive? ? 'positive' : 'negative' %>" 
                 style="width: <%= cleanliness_width %>%; background-color: <%= cleanliness_score.positive? ? '#4CAF50' : '#FF5722' %>;"></div>
          <% end %>
        </div>
        <span class="label-right">ピカピカ</span>
      </div>
    </div>

    <!-- 照明 -->
    <div class="evaluation-item">
      <span class="label-top">照明</span>
      <div class="label-container">
        <span class="label-left">暗い</span>
        <div class="bar">
          <div class="neutral"></div>
          <% lighting_score = @shop.average_lighting %>
          <% lighting_width = lighting_score.abs / 3.0 * 50 %>
          <% if lighting_score != 0 %>
            <div class="fill <%= lighting_score.positive? ? 'positive' : 'negative' %>" 
                 style="width: <%= lighting_width %>%; background-color: <%= lighting_score.positive? ? '#4CAF50' : '#FF5722' %>;"></div>
          <% end %>
        </div>
        <span class="label-right">明るい</span>
      </div>
    </div>

    <!-- 音楽 -->
    <div class="evaluation-item">
      <span class="label-top">音楽</span>
      <div class="label-container">
        <span class="label-left">クラシック</span>
        <div class="bar">
          <div class="neutral"></div>
          <% music_score = @shop.average_music %>
          <% music_width = music_score.abs / 3.0 * 50 %>
          <% if music_score != 0 %>
            <div class="fill <%= music_score.positive? ? 'positive' : 'negative' %>" 
                 style="width: <%= music_width %>%; background-color: <%= music_score.positive? ? '#4CAF50' : '#FF5722' %>;"></div>
          <% end %>
        </div>
        <span class="label-right">モダン</span>
      </div>
    </div>

    <!-- 広さ -->
    <div class="evaluation-item">
      <span class="label-top">広さ</span>
      <div class="label-container">
        <span class="label-left">狭い</span>
        <div class="bar">
          <div class="neutral"></div>
          <% space_score = @shop.average_space %>
          <% space_width = space_score.abs / 3.0 * 50 %>
          <% if space_score != 0 %>
            <div class="fill <%= space_score.positive? ? 'positive' : 'negative' %>" 
                 style="width: <%= space_width %>%; background-color: <%= space_score.positive? ? '#4CAF50' : '#FF5722' %>;"></div>
          <% end %>
        </div>
        <span class="label-right">広い</span>
      </div>
    </div>

    <!-- 活気 -->
    <div class="evaluation-item">
      <span class="label-top">活気</span>
      <div class="label-container">
        <span class="label-left">しっとり</span>
        <div class="bar">
          <div class="neutral"></div>
          <% vibrancy_score = @shop.average_vibrancy %>
          <% vibrancy_width = vibrancy_score.abs / 3.0 * 50 %>
          <% if vibrancy_score != 0 %>
            <div class="fill <%= vibrancy_score.positive? ? 'positive' : 'negative' %>" 
                 style="width: <%= vibrancy_width %>%; background-color: <%= vibrancy_score.positive? ? '#4CAF50' : '#FF5722' %>;"></div>
          <% end %>
        </div>
        <span class="label-right">ワイワイ</span>
      </div>
    </div>

    <!-- オーダーの速さ -->
    <div class="evaluation-item">
      <span class="label-top">オーダーの速さ</span>
      <div class="label-container">
        <span class="label-left">ゆったり</span>
        <div class="bar">
          <div class="neutral"></div>
          <% order_speed_score = @shop.average_order_speed %>
          <% order_speed_width = order_speed_score.abs / 3.0 * 50 %>
          <% if order_speed_score != 0 %>
            <div class="fill <%= order_speed_score.positive? ? 'positive' : 'negative' %>" 
                 style="width: <%= order_speed_width %>%; background-color: <%= order_speed_score.positive? ? '#4CAF50' : '#FF5722' %>;"></div>
          <% end %>
        </div>
        <span class="label-right">テキパキ</span>
      </div>
    </div>

    <!-- 対応スタイル -->
    <div class="evaluation-item">
      <span class="label-top">対応スタイル</span>
      <div class="label-container">
        <span class="label-left">ジェントル</span>
        <div class="bar">
          <div class="neutral"></div>
          <% service_style_score = @shop.average_service_style %>
          <% service_style_width = service_style_score.abs / 3.0 * 50 %>
          <% if service_style_score != 0 %>
            <div class="fill <%= service_style_score.positive? ? 'positive' : 'negative' %>" 
                 style="width: <%= service_style_width %>%; background-color: <%= service_style_score.positive? ? '#4CAF50' : '#FF5722' %>;"></div>
          <% end %>
        </div>
        <span class="label-right">フレンドリー</span>
      </div>
    </div>

    <!-- 会話 -->
    <div class="evaluation-item">
      <span class="label-top">会話</span>
      <div class="label-container">
        <span class="label-left">寡黙</span>
        <div class="bar">
          <div class="neutral"></div>
          <% conversation_score = @shop.average_conversation %>
          <% conversation_width = conversation_score.abs / 3.0 * 50 %>
          <% if conversation_score != 0 %>
            <div class="fill <%= conversation_score.positive? ? 'positive' : 'negative' %>" 
                 style="width: <%= conversation_width %>%; background-color: <%= conversation_score.positive? ? '#4CAF50' : '#FF5722' %>;"></div>
          <% end %>
        </div>
        <span class="label-right">おしゃべり</span>
      </div>
    </div>
  </div>

  <div class="actions">
    <% if user_signed_in? %>
      <% if current_user.id == @shop.user_id %>
        <%= link_to '編集する', edit_shop_path(@shop.id), class: 'btn btn-secondary' %>
        <%= link_to '削除する', shop_path, data: {turbo_method: :delete}, class: 'btn btn-secondary' %>
      <% else %>
      <% end %>
    <% end %>
    <%= link_to 'お店一覧に戻る', shops_path, class: 'btn btn-secondary' %>
  </div>
</div>

<%= render "shared/footer" %>