config/routes.rb
Rails.application.routes.draw do
  root to: 'shops#search'

  devise_for :users
  resources :shops, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    collection do
      get 'search', to: 'shops#search', as: 'search'
      get 'search_by_reviews', to: 'shops#search_by_reviews', as: 'search_by_reviews'
    end
    member do
      get 'reviews', to: 'shops#reviews'
      get 'photos', to: 'shops#photos'
    end
    resources :reviews, only: [:new, :create, :show, :edit, :update, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews

  validates :nickname, presence: true
  validates :gender_id, numericality: { other_than: 1, message: "can't be blank" }
  validates :age_group_id, numericality: { other_than: 1, message: "can't be blank" }

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i
  validates_format_of :password, with: PASSWORD_REGEX, message: 'is invalid. Include both letters and numbers'

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :gender
  belongs_to :age_group
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  def show
    
  end

  def edit
    
  end

  def update
    if @user.update(user_params)
      sign_in(@user, bypass: true)
      redirect_to user_path(@user)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def index
    @shops = current_user.reviews.includes(:shop).map(&:shop).uniq
  end

  private
  def user_params
    params.require(:user).permit(:nickname, :email, :password, :password_confirmation, :gender_id, :age_group_id, :profile)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render "shared/header" %>

<%= form_with model: @user, url: user_path(@user), method: :patch, class: 'edit-user-form', local: true do |f| %>
  <div class='form-wrap'>
    <div class='form-header'>
      <h1 class='form-header-text'>
        ユーザー情報編集
      </h1>
    </div>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">ニックネーム</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :nickname, class:"input-default", id:"nickname", placeholder:"例) yamada太郎", maxlength:"40" %>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">メールアドレス</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.email_field :email, class:"input-default", id:"email", placeholder:"PC・携帯どちらでも可", autofocus: true %>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">パスワード</label>
      </div>
      <%= f.password_field :password, class:"input-default", id:"password", placeholder:"6文字以上の半角英数字" %>
      <p class='info-text'>※英字と数字の両方を含めて設定してください</p>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">パスワード(確認)</label>
      </div>
      <%= f.password_field :password_confirmation, class:"input-default", id:"password-confirmation", placeholder:"同じパスワードを入力して下さい" %>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">性別</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:gender_id, Gender.all, :id, :name, {}, {class: "input-default", id: "gender"}) %>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">年代</label>
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:age_group_id, AgeGroup.all, :id, :name, {}, {class: "input-default", id: "age-group"}) %>
    </div>

    <div class="form-group">
      <div class='form-text-wrap'>
        <label class="form-text">プロフィール</label>
        <span class="indispensable">任意</span>
      </div>
      <%= f.text_area :profile, class: "input-default", id: "profile", placeholder: "プロフィールを入力してください" %>
    </div>

    <div class='actions'>
      <%= f.submit "更新する" ,class:'btn btn-secondary' %>
      <%= link_to '戻る', "/users/#{current_user.id}", class: 'btn btn-secondary' %>
    </div>
  </div>
<% end %>

<%= render "shared/footer" %>

app/views/users/index.html.erb
<%= render "shared/header" %>

<% if @shops.any? %>
  <table class="user-table">
    <thead>
      <tr>
        <th>お店の名前</th>
        <th>住所</th>
        <th>営業時間</th>
        <th>定休日</th>
        <th>詳細</th>
      </tr>
    </thead>
    <tbody>
      <% @shops.each do |shop| %>
        <% shop.reviews.where(user_id: current_user.id).each do |review| %>
          <tr>
            <td><%= shop.shop_name %></td>
            <td><%= shop.address %></td>
            <td><%= shop.opening_hours %></td>
            <td><%= shop.closed_days %></td>
            <td><%= link_to 'レビューを見る', shop_review_path(shop, review), class: 'btn btn-primary'  %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>該当するお店が見つかりませんでした。</p>
<% end %>
<%= render "shared/footer" %>

app/views/users/show.html.erb
<%= render "shared/header" %>
<div class="container">
  <div class='user-details'>
    <h1 class='user-details-header'>ユーザー情報</h1>

    <div class='user-details-group'>
      <label class="user-details-label">ニックネーム</label>
      <p class="user-details-value"><%= @user.nickname %></p>
    </div>

    <div class='user-details-group'>
      <label class="user-details-label">メールアドレス</label>
      <p class="user-details-value"><%= @user.email %></p>
    </div>

    <div class='user-details-group'>
      <label class="user-details-label">性別</label>
      <p class="user-details-value"><%= @user.gender.name %></p>
    </div>

    <div class='user-details-group'>
      <label class="user-details-label">年代</label>
      <p class="user-details-value"><%= @user.age_group.name %></p>
    </div>

    <div class='user-details-group'>
      <label class="user-details-label">プロフィール</label>
      <p class="user-details-value"><%= @user.profile.presence || "未設定" %></p>
    </div>

    <div class='actions'>
      <%= link_to '編集する', edit_user_path, class: 'btn btn-secondary' %>
      <%= link_to 'レビューしたお店を見る', users_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>
<%= render "shared/footer" %>