config/routes.rb
Rails.application.routes.draw do
  root to: 'shops#search'

  devise_for :users
  resources :shops, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    collection do
      get 'search', to: 'shops#search', as: 'search'
      get 'search_by_reviews', to: 'shops#search_by_reviews', as: 'search_by_reviews'
    end
    member do
      get 'reviews', to: 'shops#reviews'
      get 'photos', to: 'shops#photos'
    end
    resources :reviews, only: [:new, :create, :show, :edit, :update, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index]
end

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer mt-auto py-3">
    <div class="footer-container">
      <span class="text-muted">© 2024 ドコイク？</span>
    </div>
  </footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="wrapper">
      <a class="navbar-brand app-name" href="<%= root_path%>">
        <%= image_tag 'dokoiku.png', alt: 'ドコイク？', class: 'brand-logo' %>
      </a>
      <div class="nav-links">
        <div class="user-links">
          <ul class="navbar-nav">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to current_user.nickname, "/users/#{current_user.id}", class: "nav-link user-nickname" %>
              </li>
              <li class="nav-item">
                <%= link_to 'ログアウト', destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link logout" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'ログイン', new_user_session_path, class: "nav-link login" %>
              </li>
              <li class="nav-item">
                <%= link_to '新規登録', new_user_registration_path, class: "nav-link sign-up" %>
              </li>
            <% end %>
          </ul>
        </div>
        <% if user_signed_in? %>
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to '新しいお店を投稿', new_shop_path, data: { turbo: false }, class: "nav-link post-shop" %>
            </li>
          </ul>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_second-header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="wrapper">
      <a class="navbar-brand app-name" href="<%= root_path%>">
        <%= image_tag 'dokoiku.png', alt: 'ドコイク？', class: 'brand-logo' %>
      </a>
    </div>
  </nav>
</header>